import { query } from '@/lib/db';
import SummaryTableComponent from '@/components/SummaryTableComponent';
import Link from 'next/link';

export default async function SummaryPage() {
  // Fetch all rows from the new summary table generated by dbt
  const summaryData = await query(`SELECT * FROM wid_summary`);

  return (
    <main className="flex-1 max-w-7xl mx-auto w-full px-6 py-12 space-y-12 text-foreground overflow-x-hidden">
      {/* Navigation */}
      <nav className="flex items-center mb-8">
        <Link 
          href="/" 
          className="group flex items-center gap-2 text-sm font-sans text-[#666] hover:text-accent transition-colors"
        >
          <span className="text-lg group-hover:-translate-x-1 transition-transform">←</span>
          <span>Back to Main Report</span>
        </Link>
      </nav>

      {/* Hero Section */}
      <section className="mb-16 flex flex-col items-center text-center">
        <h1 className="text-5xl md:text-7xl font-serif tracking-tighter leading-[1.1] mb-6 max-w-4xl">
          Database <span className="text-accent italic">Metadata</span>
        </h1>
        <div className="max-w-3xl space-y-6 text-xl text-[#888] font-sans font-light leading-relaxed">
          <p className="text-[#ccc] font-medium">
            Explore the WID.world Summary Table
          </p>
          <p className="text-base text-[#666]">
            This table contains the comprehensive metadata and methodology notes for the indicators tracked by the World Inequality Database. Use the search to filter by country, indicator, or methodology.
          </p>
        </div>
      </section>

      {/* Table Section */}
      <section className="w-full pb-24">
        <SummaryTableComponent data={summaryData} />
      </section>
    </main>
  );
}
