/**
 * Static data loader.
 * Reads pre-exported JSON files generated by scripts/export-data.js at build time.
 * No native database dependencies at runtime - works perfectly on Vercel.
 */

import path from 'path';
import fs from 'fs';

function loadJson(filename: string): any[] {
  const filePath = path.join(process.cwd(), 'src/data', filename);
  if (!fs.existsSync(filePath)) {
    console.error(`Data file not found: ${filePath}`);
    return [];
  }
  return JSON.parse(fs.readFileSync(filePath, 'utf-8'));
}

export function getGlobalData(): any[] {
  return loadJson('global-data.json');
}

export function getGapData(): any[] {
  return loadJson('gap-data.json');
}

export function getSummaryData(): any[] {
  return loadJson('summary-data.json');
}
